services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=meeting_room_booking_system'
      - 'POSTGRES_PASSWORD=mypassword'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433'
